name: Static publish to gh-pages

on: 
  repository_dispatch:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - name: Deploy to github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
