name: Static publish to gh-pages

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - name: Deploy to github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
